import type { Map, RequestParameters } from "mapbox-gl";
import { TileTuple } from "./utils";
import type { Loader } from "zarr-js";
import Tile from "./tile";
type RGB = [number, number, number];
export interface ZarrLayerProps {
    map: Map;
    id: string;
    source: string;
    version: "v2" | "v3";
    variable: string;
    selector: Record<string, number>;
    colormap: RGB[];
    vmin: number;
    vmax: number;
    opacity?: number;
    minRenderZoom?: number;
    invalidate?: () => void;
    transformRequest?: (url: string) => RequestParameters | Promise<RequestParameters>;
}
export declare class ZarrLayer {
    type: "custom";
    renderingMode: "2d";
    map: Map;
    id: string;
    zarrSource: string;
    zarrVersion: "v2" | "v3";
    variable: string;
    selector: Record<string, number>;
    invalidate: () => void;
    transformRequest?: (url: string) => RequestParameters | Promise<RequestParameters>;
    cmapLength: number;
    cmap: Float32Array;
    vmin: number;
    vmax: number;
    opacity: number;
    minRenderZoom: number;
    loaders: Record<string, Loader>;
    tiles: Record<string, Tile>;
    maxZoom: number;
    fillValue: number;
    private gl;
    private program;
    private scaleLoc;
    private shiftXLoc;
    private shiftYLoc;
    private matrixLoc;
    private vminLoc;
    private vmaxLoc;
    private opacityLoc;
    private noDataLoc;
    private vertexLoc;
    private cmapTex;
    private cmapLoc;
    private vertexArr;
    private pixCoordArr;
    private texLoc;
    private pixCoordLoc;
    private frameBuffers;
    private isUpdating;
    private canvasWidth;
    private canvasHeight;
    private renderProgram;
    private renderVertexLoc;
    private renderTexLoc;
    private vertexBuffer;
    constructor({ id, source, version, variable, selector, map, colormap, vmin, vmax, opacity, minRenderZoom, invalidate, transformRequest, }: ZarrLayerProps);
    setOpacity(opacity: number): void;
    setVminVmax(vmin: number, vmax: number): void;
    setVariable(variable: string): Promise<void>;
    setSelector(selector: Record<string, number>): Promise<void>;
    prefetchTileData(): Promise<void>;
    getVisibleTiles(): TileTuple[];
    prepareTiles(): Promise<void>;
    getTileValue(lng: number, lat: number, x: number, y: number): Promise<number>;
    onAdd(_map: Map, gl: WebGL2RenderingContext): Promise<void>;
    prerender(gl: WebGL2RenderingContext, matrix: number[]): void;
    render(gl: WebGL2RenderingContext, _matrix: number[]): void;
}
export {};
